<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <PackageId>Fluidify</PackageId>
    <Version>0.1.0</Version>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageOutputPath>$(MSBuildThisFileDirectory)../../artifacts/pkg</PackageOutputPath>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <DevelopmentDependency>true</DevelopmentDependency>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <NoWarn>NU5128;NU5100</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Fluid.Core" Version="2.31.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="17.3.2" PrivateAssets="all" ExcludeAssets="runtime" />
  </ItemGroup>

  <ItemGroup>
    <None Include="build\Fluidify.targets" Pack="true" PackagePath="build" Visible="false" />
  </ItemGroup>

  <PropertyGroup>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);PackTaskDlls</TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>

  <Target Name="PackTaskDlls">
    <ItemGroup>
      <TfmSpecificPackageFile Include="$(OutputPath)**/*.dll" PackagePath="tasks/netstandard2.0" />
    </ItemGroup>
  </Target>

</Project>
